version: '3.8'
services:
  postgres-local:
    image: postgres:13
    container_name: clean-architecture-db-local
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: local_db
    volumes:
      - postgres-local-data:/var/lib/postgresql/data

volumes:
  postgres-local-data:
    name: clean-architecture-local-db-volume
